# Generated by Django 4.1.5 on 2023-01-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('full_text', models.TextField(verbose_name='Full text')),
                ('date', models.DateTimeField(verbose_name='Date create')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'New',
                'verbose_name_plural': 'News',
            },
        ),
    ]
