# Generated by Django 4.1.5 on 2023-01-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='full_text',
            field=models.TextField(default='Title text', verbose_name='Full text'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='Title news', max_length=80, verbose_name='Title'),
        ),
    ]
