# Generated by Django 4.1.5 on 2023-01-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_full_text_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='Title news', max_length=150, verbose_name='Title'),
        ),
    ]
