# Generated by Django 4.1.5 on 2023-01-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.FileField(upload_to='news/', verbose_name='Image'),
        ),
    ]
