# Generated by Django 4.1.5 on 2023-01-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.FileField(default=None, null=True, upload_to='news/', verbose_name='Image'),
        ),
    ]
